[build]
  command = "npm run build"
  publish = "dist"
[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[dev]
  command = "npm run dev"

[build.environment]
  NODE_VERSION = "20"

